@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #EEEBDC

skinparam sequence {
    LifeLineBackgroundColor grey
}

autonumber

participant "retail-sales" as sales
participant "DP" as dp
participant "DB" as db
participant "ES" as es

dp -> db : 拉数据
note left
    前提：retail-sales 蓝绿发布中
    已经开始了 ES 新增和更新逻辑
    此时实时/离线拉取数据到 DP
    DP 刷入 ES
end note
activate db
return 返回

dp -> es : 写入
activate es
return 返回

sales -> DB : 根据 kdtId 拉取 15 天内的数据
activate DB
return 返回

sales -> es : 复用 ES创建 逻辑写入 ES
activate es
return 返回

@enduml