@startuml
'https://plantuml.com/sequence-diagram
skinparam backgroundColor #EEEBDC
skinparam sequence {
    LifeLineBackgroundColor grey
}

autonumber

box "Out Service"
participant "salesman-api" as salesman
end box

box "Internal Service"
participant "retail-sales" as sales
participant "ES" as es
end box

salesman ->o sales : 支付消息
activate sales

sales -> es : 同步 ES
activate es
return 返回
return 返回

@enduml