@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #EEEBDC
hide footbox

skinparam sequence {
    LifeLineBackgroundColor grey
}

autonumber

participant "retail-sales" as sales
participant "DP" as dp
participant "DB" as db
participant "ES" as es
participant "DB-mi" as db_mi

group DP-第一阶段[全量]
    dp -> db : 全量拉数据
    note left
        前提：retail-sales 蓝绿发布中
        已经开始了 ES 新增和更新逻辑
        此时实时/离线拉取数据到 DP
        DP 刷入 ES
    end note
    activate db
    return 返回
    dp -> es : 写入 es
    activate es
    return 返回
end

group DP-第二阶段准备[增量]
    dp -> db : 拉取增量数据
    note left
        updated_at >= ?
            or
        created_at >= ?
    end note
    activate db
    return 返回
    dp -> db_mi : 导出
    activate db_mi
     return 返回
end

group 接口-第二阶段[增量]
    sales -> db_mi : 拉取增量数据
    note left
        DP 开始时间以后的数据
    end note
    activate db_mi
    return 返回

    sales -> es : 复用 ES创建逻辑写入或更新 ES
    activate es
    return 返回
end

@enduml